version: "3.2"

services:
  waproject-mongo:
    image: mongo:4.2
    container_name: waproject-mongo
    restart: always
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  waproject-api:
    image: node:latest
    container_name: waproject-api
    restart: always
    depends_on:
      - waproject-mongo
    ports:
      - ${PORT}:3333
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
